apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: Kustomize
resources:
  - ./metallb/pool.yaml
  - ./storage/default-storage-class.yaml
  - ./jellyfin/jellyfin-data-pv.yaml
#  - ./jellyfin/jellyfin-data-pvc.yaml
  - ./jellyfin/jellyfin-pv.yaml
  - ./jellyfin/jellyseerr-pv.yaml
  - ./jellyfin/radarr-pv.yaml
  - ./jellyfin/readarr-pv.yaml
  - ./jellyfin/sonarr-pv.yaml
  - ./jellyfin/jackett-pv.yaml
  - ./homarr/pvs.yaml