apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "jellyfin-media"
  name: "jellyfin-media-storage"
spec:
  storageClassName: "local-storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Gi"