#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: lscr.io/linuxserver/jackett
  # @default -- chart.appVersion
  tag: latest
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [image docs](https://docs.linuxserver.io/images/docker-jackett#environment-variables-e) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: Etc/UTC
#  PUID: 1000
#  PGID: 1000
  AUTO_UPDATE: true

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 9117

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    hosts:
      - host: "jackett.dio.porco"
        paths:
          - path: /
            pathType: ImplementationSpecific

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: /config
    size: 1Gi  # adjust size as needed
    storageClass: local-storage

  media:
    enabled: true
    mountPath: /media
    hostPath: /home/sleeper/media-volume  # your host path
    type: hostPath

  torrentblackhole:
    enabled: true
    mountPath: /downloads
    hostPath: /home/sleeper/media-volume/downloads  # your host path
    type: hostPath

#podSecurityContext:
#  runAsUser: 1000
#  runAsGroup: 1000
#
#securityContext:
#  runAsUser: 1000
#  runAsGroup: 1000
#  fsGroup: 1000