apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-plex-data
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: /home/sleeper/media-volume