repositories:
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: next-cloud
    url: https://nextcloud.github.io/helm/
  - name: jellyfin
    url: https://jellyfin.github.io/jellyfin-helm
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/
  - name: homarr
    url: https://oben01.github.io/charts/
#  - name: plex
#    url: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
---
releases:
  # Load balancer
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.14.5

  # pihole
  - name: pihole
    namespace: pihole-system
    chart: mojo2600/pihole
    version: 2.18.0
    values:
      - ./values/pihole.values.yaml

  # Ingress for local network
  - name: ingress-nginx-internal
    namespace: nginx-system
    chart: ingress-nginx/ingress-nginx
    version: 4.10.1
    values:
      - ./values/nginx-internal.values.yaml

  # Automatic DNS for pihole
  - name: externaldns-pihole
    namespace: pihole-system
    chart: bitnami/external-dns
    version: 8.0.1
    values:
      - ./values/externaldns.values.yaml

  # Internal Cloud
  - name: nextcloud
    namespace: nextcloud
    chart: nextcloud/nextcloud
    values:
    - ./values/next-cloud.values.yaml

#  - name: plex
#    namespace: plex-media
#    chart: plex/plex-media-server
#    values:
#    - ./values/plex.values.yaml

  - name: jellyfin
    namespace: jellyfin-media
    chart: jellyfin/jellyfin
    values:
    - ./values/jellyfin.values.yaml

  - name: jellyseer
    namespace: jellyfin-media
    chart: ../helm-charts/jellyseerr
    values:
    - ./values/jellyseer.values.yaml

#  - name: sonarr
#    namespace: jellyfin-media
#    chart: ../helm-charts/sonarr
#    values:
#    - ./values/sonarr.values.yaml
#
#  - name: readarr
#    namespace: jellyfin-media
#    chart: ../helm-charts/readarr
#    values:
#    - ./values/readarr.values.yaml
#
#  - name: radarr
#    namespace: jellyfin-media
#    chart: ../helm-charts/radarr
#    values:
#    - ./values/radarr.values.yaml

  - name: sonarr
    namespace: jellyfin-media
    chart: k8s-at-home/sonarr
    values:
    - ./values/sonarr.values.yaml

  - name: readarr
    namespace: jellyfin-media
    chart: k8s-at-home/readarr
    values:
    - ./values/readarr.values.yaml

  - name: radarr
    namespace: jellyfin-media
    chart: k8s-at-home/radarr
    values:
    - ./values/radarr.values.yaml

  - name: qbittorrent
    namespace: jellyfin-media
    chart: k8s-at-home/qbittorrent
    values:
    - ./values/qbittorrent.values.yaml

  - name: jackett
    namespace: jellyfin-media
    chart: k8s-at-home/jackett
    values:
    - ./values/jackett.values.yaml

  - name: homarr
    namespace: homarr
    chart: homarr/homarr
    values:
    - ./values/homarr.values.yaml